import Head from 'next/head'
import Link from "next/link";

import styles from '../styles/Home.module.css'
import Layout from "../components/layout";
import React from "react";
import {pageTitle} from "./documents";

export default function Home() {
    return (
        <Layout home>
            <Head>
                <title>Create Next App</title>
                <meta name={'og:title'} content={ pageTitle  }/>
                <meta name="description" content="Generated by create next app"/>
            </Head>
            <section>
                <h1 className={styles.title}>
                    Welcome to <a href="https://nextjs.org">Next.js!</a>
                </h1>

                <p className={styles.description}>
                    Get started by editing{' '}
                    <code className={styles.code}>pages/index.js</code>
                </p>

                <div className={styles.grid}>
                    <Link href={'/documents'}>
                        <a className={styles.card}>
                            <h2>Documentation &rarr;</h2>
                        </a>
                    </Link>

                    <a href="https://nextjs.org/learn" className={styles.card}>
                        <h2>Learn &rarr;</h2>
                    </a>

                    <a
                        href="https://github.com/vercel/next.js/tree/master/examples"
                        className={styles.card}
                    >
                        <h2>Examples &rarr;</h2>
                    </a>

                    <Link
                        href={'https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'}>
                        <a className={styles.card}>
                            <h2>Deploy &rarr;</h2>
                        </a>
                    </Link>
                </div>
            </section>
        </Layout>
    )
}
